version: '3'
services:
  my-scoring-system:
    build:
      context: .
    container_name: my-scoring-system
    restart: always
    environment:
      TZ: Asia/Tehran
    volumes:
       - ./score:/app/score
       - ./score.log:/app/score.log
    ports:
      - 8000:80
    networks:
      - my-scoring-system

networks:
  my-scoring-system:
    external: false

volumes:
  dbdata:
    driver: local