version: '3'
services:
  my-scoring-system:
    build:
      context: .
    container_name: my-scoring-system
    restart: always
    depends_on:
      - my-scoring-system-db
    networks:
      - my-scoring-system

networks:
  my-scoring-system:
    external: false

volumes:
  dbdata:
    driver: local