#! /bin/bash
ACTION=$1
SCORE_OBJECT=$2
TITLE=$3
SCORE=$4
ID=$3

case $ACTION in
  "get")
    curl localhost:8000/$SCORE_OBJECT -s | jq .
    ;;
  "create")
    curl -XPUT localhost:8000/$SCORE_OBJECT --data "{\"title\":\"$3\", \"score\": \"$4\"}" -H 'Content-Type: application/json'
    ;;
  "achieve")
    curl -XPOST localhost:8000/achieve/$SCORE_OBJECT/$3
    ;;
  *)
    echo "Gomsho"
    ;;
esac